import MainLayout from "../ui/components/dashboardLayout";
// import { Inter } from "next/font/google";
// import "../globals.css";
// import "@flaticon/flaticon-uicons/css/regular/rounded.css";
// import "@flaticon/flaticon-uicons/css/solid/rounded.css";
// import "@flaticon/flaticon-uicons/css/brands/all.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({ children }) {
  return (
    <section>{
      <MainLayout page={children}/>}
    </section>
)}