import MainLayout from "../ui/components/dashboardLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <section>
        <MainLayout page={children}/>
    </section>
)}